/* The following code was generated by JFlex 1.5.1 */

package lexer;

import java.util.*;
import com.intellij.lexer.*;
import com.intellij.psi.*;
import com.intellij.psi.tree.IElementType;
import generated.GeneratedTypes;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.5.1
 * from the specification file <tt>/Users/atsky/work/haskell-idea-plugin/grammar/src/lexer/Haskell.flex</tt>
 */
class _KitHaskellLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int BLOCK_COMMENT = 2;
  public static final int TEX = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\3\0\1\3\1\0\1\1\3\0\1\1\1\2\1\23\1\1\1\1"+
    "\22\0\1\1\1\0\1\0\1\0\1\0\1\0\1\0\1\3\2\0"+
    "\1\0\1\0\1\0\1\13\1\24\1\0\1\3\1\3\1\3\1\3"+
    "\1\3\3\3\2\3\1\0\1\0\4\0\1\0\1\4\1\4\1\4"+
    "\1\4\1\4\1\4\1\4\1\4\1\4\1\4\1\4\1\4\1\4"+
    "\1\4\1\4\1\4\1\4\1\4\1\4\1\4\1\4\1\4\1\4"+
    "\1\4\1\4\1\4\1\0\1\10\1\0\1\0\1\5\1\0\1\5"+
    "\1\14\1\6\1\7\1\15\1\5\1\16\1\33\1\17\2\5\1\31"+
    "\1\25\1\20\1\12\1\26\1\5\1\27\1\5\1\11\1\30\1\5"+
    "\1\32\1\5\2\5\1\21\1\0\1\22\1\0\6\0\1\23\33\0"+
    "\11\0\1\5\2\0\1\0\4\0\2\0\1\0\1\5\3\0\1\0"+
    "\1\5\1\0\3\0\1\0\27\4\1\0\7\4\30\5\1\0\10\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\2\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\2\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\2\4\1\5"+
    "\1\4\1\5\1\4\3\5\2\4\1\5\1\4\1\5\2\4\1\5"+
    "\3\4\2\5\4\4\1\5\2\4\1\5\3\4\3\5\2\4\1\5"+
    "\2\4\1\5\1\4\1\5\1\4\1\5\2\4\1\5\1\4\2\5"+
    "\1\4\1\5\2\4\1\5\3\4\1\5\1\4\1\5\2\4\2\5"+
    "\1\0\1\4\3\5\4\0\1\4\1\0\1\5\1\4\1\0\1\5"+
    "\1\4\1\0\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4"+
    "\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\2\5\1\4"+
    "\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4"+
    "\1\5\1\4\1\5\1\4\1\5\1\4\2\5\1\4\1\0\1\5"+
    "\1\4\1\5\3\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\7\5\2\4\1\5\2\4\2\5\1\4\1\5\4\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\105\5\1\0\44\5"+
    "\7\0\2\5\4\0\14\0\16\0\5\5\7\0\1\0\1\0\1\0"+
    "\21\0\105\0\1\5\52\0\1\4\1\5\1\4\1\5\1\0\1\0"+
    "\1\4\1\5\2\0\4\5\1\0\5\0\2\0\1\4\1\0\3\4"+
    "\1\0\1\4\1\0\2\4\1\5\21\4\1\0\11\4\43\5\1\4"+
    "\2\5\3\4\3\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4"+
    "\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4"+
    "\1\5\1\4\1\5\1\4\1\5\1\4\5\5\1\4\1\5\1\0"+
    "\1\4\1\5\2\4\2\5\63\4\60\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\0\7\0\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\2\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\2\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\11\0\46\4"+
    "\3\0\6\0\1\0\47\5\1\0\2\0\4\0\1\0\56\0\1\0"+
    "\1\0\1\0\2\0\1\0\2\0\1\0\54\0\2\0\21\0\12\0"+
    "\13\0\1\0\2\0\2\0\112\0\4\0\146\0\1\0\11\0\1\0"+
    "\12\0\1\0\23\0\2\0\1\0\16\0\350\0\4\0\66\0\17\0"+
    "\37\0\1\0\u0105\0\2\0\12\0\1\0\201\0\2\0\6\0\2\0"+
    "\364\0\2\0\176\0\1\0\202\0\10\0\204\0\1\0\371\0\1\0"+
    "\172\0\1\0\112\0\1\0\17\0\1\0\12\0\2\0\245\0\27\0"+
    "\2\0\6\0\24\0\1\0\1\0\1\0\1\0\1\0\1\0\4\0"+
    "\107\0\1\0\70\0\10\0\1\0\6\0\1\0\15\0\157\0\6\0"+
    "\116\0\2\0\46\4\1\0\1\4\5\0\1\4\55\0\1\0\u0264\0"+
    "\11\0\47\0\12\0\146\0\1\0\u026c\0\2\0\54\0\2\0\116\0"+
    "\3\0\107\0\2\0\235\0\3\0\1\0\4\0\44\0\13\0\u0135\0"+
    "\1\0\3\0\2\0\230\0\42\0\36\0\2\0\200\0\7\0\1\0"+
    "\6\0\254\0\21\0\11\0\11\0\177\0\4\0\73\0\5\0\76\0"+
    "\2\0\100\0\10\0\13\0\1\0\54\0\300\5\100\0\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\11\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\11\5\10\4\6\5\2\0\6\4"+
    "\2\0\10\5\10\4\10\5\10\4\6\5\2\0\6\4\2\0\10\5"+
    "\1\0\1\4\1\0\1\4\1\0\1\4\1\0\1\4\10\5\10\4"+
    "\16\5\2\0\10\5\10\0\10\5\10\0\10\5\10\0\5\5\1\0"+
    "\2\5\4\4\1\0\1\0\1\5\3\0\3\5\1\0\2\5\4\4"+
    "\1\0\3\0\4\5\2\0\2\5\4\4\1\0\3\0\10\5\5\4"+
    "\3\0\2\0\3\5\1\0\2\5\4\4\1\0\2\0\21\0\30\0"+
    "\1\23\1\23\6\0\57\0\22\0\1\5\10\0\5\0\1\5\12\0"+
    "\5\0\1\0\15\5\3\0\33\0\105\0\2\0\1\4\4\0\1\4"+
    "\2\0\1\5\3\4\2\5\3\4\1\5\1\0\1\4\3\0\5\4"+
    "\6\0\1\4\1\0\1\4\1\0\1\4\1\0\4\4\1\0\1\5"+
    "\4\4\1\5\4\0\1\5\2\0\2\5\2\4\5\0\1\4\4\5"+
    "\4\0\1\5\1\0\20\0\20\4\20\5\3\0\1\4\1\5\13\0"+
    "\u0264\0\14\0\47\0\31\0\13\0\121\0\32\0\32\4\32\5\26\0"+
    "\u0200\0\1\0\165\0\36\0\u03b9\0\3\0\12\0\246\0\57\4\1\0"+
    "\57\5\1\0\1\4\1\5\3\4\2\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\4\4\1\5\1\4\2\5\1\4\10\5\3\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\2\5\6\0\1\4"+
    "\1\5\1\4\1\5\3\0\1\4\1\5\5\0\4\0\1\0\2\0"+
    "\46\5\1\0\1\5\5\0\1\5\102\0\1\0\217\0\57\0\1\0"+
    "\14\0\104\0\32\0\1\0\131\0\14\0\326\0\32\0\14\0\5\0"+
    "\4\0\3\0\31\0\17\0\1\0\5\0\2\0\5\0\3\0\133\0"+
    "\2\0\3\0\1\0\132\0\1\0\224\0\2\0\4\0\12\0\40\0"+
    "\44\0\34\0\37\0\13\0\36\0\10\0\1\0\17\0\40\0\12\0"+
    "\47\0\17\0\77\0\1\0\u0100\0\u19c0\0\100\0\u5690\0\67\0\67\0"+
    "\2\0\u010d\0\3\0\60\0\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5"+
    "\5\0\1\0\12\0\1\0\1\0\1\4\1\5\1\4\1\5\1\4"+
    "\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4"+
    "\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\132\0"+
    "\6\0\10\0\27\0\11\0\2\0\1\4\1\5\1\4\1\5\1\4"+
    "\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\3\5\1\4"+
    "\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4"+
    "\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4"+
    "\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4"+
    "\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4"+
    "\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4"+
    "\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4"+
    "\12\5\1\4\1\5\1\4\1\5\2\4\1\5\1\4\1\5\1\4"+
    "\1\5\1\4\1\5\1\4\1\5\1\0\2\0\1\4\1\5\1\4"+
    "\1\5\1\0\1\4\1\5\1\4\1\5\14\0\1\4\1\5\1\4"+
    "\1\5\1\4\1\5\1\4\1\5\1\4\1\5\1\4\115\0\3\5"+
    "\55\0\4\0\12\0\4\0\72\0\4\0\126\0\2\0\50\0\3\0"+
    "\63\0\2\0\57\0\1\0\141\0\15\0\20\0\2\0\174\0\4\0"+
    "\27\0\3\0\144\0\2\0\20\0\2\0\371\0\1\0\u4f14\0\7\5"+
    "\14\0\5\5\21\0\1\0\210\0\20\0\u017c\0\2\0\274\0\2\0"+
    "\22\0\12\0\26\0\43\0\1\0\23\0\1\0\4\0\225\0\17\0"+
    "\12\0\7\0\32\4\6\0\32\5\13\0\172\0\7\0\1\0\7\0"+
    "\15\0\2\0\2\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\4\1\5\2\6\1\7"+
    "\1\10\1\11\2\6\3\12\2\1\1\6\1\13\2\6"+
    "\1\14\1\15\1\1\1\0\3\6\1\0\3\6\1\0"+
    "\2\6\1\16\1\0\1\17\1\20\6\0\1\21";

  private static int [] zzUnpackAction() {
    int [] result = new int[48];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\34\0\70\0\124\0\160\0\124\0\214\0\250"+
    "\0\304\0\340\0\124\0\124\0\374\0\u0118\0\124\0\u0134"+
    "\0\u0150\0\u016c\0\u0188\0\u01a4\0\124\0\u01c0\0\u01dc\0\124"+
    "\0\124\0\u01f8\0\u0214\0\u0230\0\u024c\0\u0268\0\u0284\0\u02a0"+
    "\0\u02bc\0\u02d8\0\u02f4\0\u0310\0\u032c\0\250\0\u0348\0\250"+
    "\0\250\0\u0364\0\u0380\0\u039c\0\u03b8\0\u03d4\0\u03f0\0\124";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[48];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\6\1\4\1\7\3\10\1\4\2\10"+
    "\1\4\3\10\1\11\1\10\1\12\1\13\1\0\1\14"+
    "\1\15\4\10\1\16\1\10\13\17\1\20\5\17\1\21"+
    "\1\17\1\0\10\17\10\22\1\23\23\22\35\0\1\5"+
    "\35\0\5\7\1\0\2\7\1\0\5\7\4\0\7\7"+
    "\3\0\5\10\1\0\2\10\1\0\5\10\4\0\7\10"+
    "\3\0\5\10\1\0\2\10\1\0\5\10\4\0\1\24"+
    "\6\10\13\0\1\25\23\0\5\10\1\0\1\10\1\26"+
    "\1\0\5\10\4\0\7\10\3\0\5\10\1\0\2\10"+
    "\1\0\5\10\4\0\6\10\1\27\22\0\1\30\24\0"+
    "\1\31\20\0\10\22\1\0\23\22\10\0\1\32\3\0"+
    "\1\33\22\0\5\10\1\0\2\10\1\0\5\10\4\0"+
    "\1\10\1\34\5\10\3\0\4\10\1\35\1\0\2\10"+
    "\1\0\5\10\4\0\7\10\3\0\5\10\1\0\2\10"+
    "\1\0\1\10\1\36\3\10\4\0\7\10\10\0\1\32"+
    "\40\0\1\37\21\0\5\10\1\0\1\10\1\40\1\0"+
    "\5\10\4\0\7\10\3\0\5\10\1\0\2\10\1\0"+
    "\5\10\4\0\3\10\1\41\3\10\3\0\5\10\1\0"+
    "\2\10\1\0\5\10\4\0\2\10\1\42\4\10\16\0"+
    "\1\43\20\0\5\10\1\0\2\10\1\0\5\10\4\0"+
    "\2\10\1\44\4\10\3\0\5\10\1\0\2\10\1\0"+
    "\5\10\4\0\4\10\1\45\2\10\3\0\5\10\1\0"+
    "\2\10\1\0\1\10\1\46\3\10\4\0\7\10\17\0"+
    "\1\47\17\0\5\10\1\0\1\50\1\10\1\0\5\10"+
    "\4\0\7\10\3\0\5\10\1\0\2\10\1\0\1\10"+
    "\1\51\3\10\4\0\7\10\20\0\1\52\34\0\1\53"+
    "\20\0\1\54\37\0\1\55\30\0\1\56\41\0\1\57"+
    "\40\0\1\60\11\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1036];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\1\1\11\1\1\1\11\4\1\2\11\2\1"+
    "\1\11\5\1\1\11\2\1\2\11\1\1\1\0\3\1"+
    "\1\0\3\1\1\0\3\1\1\0\2\1\6\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[48];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char[] zzBuffer = new char[0];

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */
    private int commentStart;
    private int commentDepth;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  _KitHaskellLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  _KitHaskellLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader
             (in, java.nio.charset.Charset.forName("UTF-8")));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 3346) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer.toString().toCharArray();
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { return GeneratedTypes.BLOCK_COMMENT;
          }
        case 18: break;
        case 2: 
          { return TokenType.BAD_CHARACTER;
          }
        case 19: break;
        case 3: 
          { return TokenType.WHITE_SPACE;
          }
        case 20: break;
        case 4: 
          { return GeneratedTypes.NEW_LINE;
          }
        case 21: break;
        case 5: 
          { return GeneratedTypes.CONID;
          }
        case 22: break;
        case 6: 
          { return GeneratedTypes.VARID;
          }
        case 23: break;
        case 7: 
          { return GeneratedTypes.OCURLYID;
          }
        case 24: break;
        case 8: 
          { return GeneratedTypes.CCURLYID;
          }
        case 25: break;
        case 9: 
          { return GeneratedTypes.DOT;
          }
        case 26: break;
        case 10: 
          { 
          }
        case 27: break;
        case 11: 
          { yybegin(BLOCK_COMMENT);
    commentDepth = 0;
    commentStart = getTokenStart();
          }
        case 28: break;
        case 12: 
          { if (commentDepth > 0) {
            commentDepth--;
        }
        else {
             int state = yystate();
             yybegin(YYINITIAL);
             zzStartRead = commentStart;
             return GeneratedTypes.BLOCK_COMMENT;
        }
          }
        case 29: break;
        case 13: 
          { commentDepth++;
          }
        case 30: break;
        case 14: 
          { return GeneratedTypes.WHEREID;
          }
        case 31: break;
        case 15: 
          { return GeneratedTypes.IMPORTID;
          }
        case 32: break;
        case 16: 
          { return GeneratedTypes.MODULEID;
          }
        case 33: break;
        case 17: 
          { yybegin(YYINITIAL); return GeneratedTypes.BLOCK_COMMENT;
          }
        case 34: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            switch (zzLexicalState) {
            case BLOCK_COMMENT: {
              int state = yystate();
        yybegin(YYINITIAL);
        zzStartRead = commentStart;
        return GeneratedTypes.BLOCK_COMMENT;
            }
            case 49: break;
            default:
            return null;
            }
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
